import type {
  Movie,
  OTTProvider,
  Mood,
  Genre,
  Language,
  Actor,
} from '../types';
import { PROVIDER_REGISTRY } from './providers';

// ===========================
// OTT Providers
// ===========================
export const OTT_PROVIDERS: Record<string, OTTProvider> = PROVIDER_REGISTRY as unknown as Record<string, OTTProvider>;

// ===========================
// Moods
// ===========================
export const MOODS: Mood[] = [
  { id: 'adventurous', label: 'Adventurous', icon: 'Compass', description: 'Epic journeys & explorations' },
  { id: 'romantic', label: 'Romantic', icon: 'Heart', description: 'Love stories & connections' },
  { id: 'thrilling', label: 'Thrilling', icon: 'Zap', description: 'Edge-of-seat suspense' },
  { id: 'funny', label: 'Funny', icon: 'Laugh', description: 'Laugh-out-loud comedies' },
  { id: 'dark', label: 'Dark', icon: 'Moon', description: 'Intense & thought-provoking' },
  { id: 'feel-good', label: 'Feel Good', icon: 'Sun', description: 'Uplifting & wholesome' },
  { id: 'emotional', label: 'Emotional', icon: 'Droplets', description: 'Moving & heartfelt stories' },
  { id: 'inspiring', label: 'Inspiring', icon: 'Sparkles', description: 'Motivating & empowering' },
  { id: 'chill', label: 'Chill', icon: 'Coffee', description: 'Relaxed & easygoing' },
  { id: 'scary', label: 'Scary', icon: 'Ghost', description: 'Horror & supernatural' },
  { id: 'mind-bending', label: 'Mind-Bending', icon: 'Brain', description: 'Complex & cerebral' },
  { id: 'action-packed', label: 'Action-Packed', icon: 'Flame', description: 'High-octane & explosive' },
];

// ===========================
// Genres
// ===========================
export const GENRES: Genre[] = [
  { id: 'action', label: 'Action' },
  { id: 'comedy', label: 'Comedy' },
  { id: 'drama', label: 'Drama' },
  { id: 'thriller', label: 'Thriller' },
  { id: 'romance', label: 'Romance' },
  { id: 'sci-fi', label: 'Sci-Fi' },
  { id: 'horror', label: 'Horror' },
  { id: 'documentary', label: 'Documentary' },
  { id: 'animation', label: 'Animation' },
  { id: 'crime', label: 'Crime' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'biography', label: 'Biography' },
  { id: 'musical', label: 'Musical' },
  { id: 'mystery', label: 'Mystery' },
  { id: 'sport', label: 'Sport' },
];

// ===========================
// Languages
// ===========================
export const LANGUAGES: Language[] = [
  { id: 'hindi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { id: 'english', label: 'English', nativeLabel: 'English' },
  { id: 'tamil', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { id: 'telugu', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { id: 'malayalam', label: 'Malayalam', nativeLabel: 'മലയാളം' },
  { id: 'korean', label: 'Korean', nativeLabel: '한국어' },
  { id: 'japanese', label: 'Japanese', nativeLabel: '日本語' },
  { id: 'marathi', label: 'Marathi', nativeLabel: 'मराठी' },
  { id: 'bengali', label: 'Bengali', nativeLabel: 'বাংলা' },
];

// ===========================
// Movies Dataset
// ===========================
export const MOVIES: Movie[] = [
  {
    id: 1,
    type: 'movie',
    title: 'Dune: Part Two',
    year: 2024,
    rating: 8.5,
    voteCount: 420000,
    runtime: 166,
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.',
    tagline: 'Long live the fighters.',
    posterPath: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    genres: ['sci-fi', 'action', 'drama'],
    language: 'english',
    providers: ['prime-video', 'apple-tv'],
    isFree: false,
    director: 'Denis Villeneuve',
    trailerKey: 'Way9Dexny3w',
    aiInsight: 'A cinematic triumph — Villeneuve transforms Herbert\'s dense mythology into visceral, breathtaking spectacle. Perfect if you want to feel genuinely transported.',
    isTrending: true,
    isHollywood: true,
    isTopRated: true,
    cast: [
      { id: 1, name: 'Timothée Chalamet', character: 'Paul Atreides', profilePath: 'https://image.tmdb.org/t/p/w185/SA7p1JbdHMBMVbQxpLzoHMkFvQU.jpg' },
      { id: 2, name: 'Zendaya', character: 'Chani', profilePath: 'https://image.tmdb.org/t/p/w185/6TE2AlOUqVMqejOoRKdH4yCv9eZ.jpg' },
      { id: 3, name: 'Rebecca Ferguson', character: 'Lady Jessica', profilePath: 'https://image.tmdb.org/t/p/w185/lJloTOheuQSirSLXNA3JHsrMNfH.jpg' },
    ],
  },
  {
    id: 2,
    type: 'movie',
    title: 'RRR',
    year: 2022,
    rating: 7.9,
    voteCount: 390000,
    runtime: 182,
    overview: 'A fictional story about two legendary revolutionaries and their journey far from home before they started fighting for their country in the 1920s.',
    tagline: 'Rise. Roar. Revolt.',
    posterPath: 'https://image.tmdb.org/t/p/w500/nEufeZlyAsvobPkExAQBbQj6cLT.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/6OEBp0Gqv6DsOgi8diPUslT2kbA.jpg',
    genres: ['action', 'drama'],
    language: 'telugu',
    providers: ['netflix', 'prime-video'],
    isFree: false,
    director: 'S. S. Rajamouli',
    trailerKey: 'f_AZMVaaVCo',
    aiInsight: 'Pure cinematic adrenaline. Two protagonists, one mission, zero compromises on spectacle. The Naatu Naatu scene alone is worth it.',
    isTrending: true,
    isBollywood: true,
    isTopRated: true,
    cast: [
      { id: 4, name: 'N. T. Rama Rao Jr.', character: 'Komaram Bheem', profilePath: null },
      { id: 5, name: 'Ram Charan', character: 'Alluri Sitarama Raju', profilePath: null },
      { id: 6, name: 'Alia Bhatt', character: 'Sita', profilePath: null },
    ],
  },
  {
    id: 3,
    type: 'movie',
    title: 'Oppenheimer',
    year: 2023,
    rating: 8.3,
    voteCount: 610000,
    runtime: 180,
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    tagline: 'The world forever changes.',
    posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    genres: ['drama', 'biography', 'thriller'],
    language: 'english',
    providers: ['prime-video'],
    isFree: false,
    director: 'Christopher Nolan',
    trailerKey: 'uYPbbksJxIg',
    aiInsight: 'Nolan\'s magnum opus. Three hours that feel like three minutes. The moral weight of every scene will stay with you long after the credits roll.',
    isTopRated: true,
    isHollywood: true,
    isAIPick: true,
    cast: [
      { id: 7, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profilePath: null },
      { id: 8, name: 'Emily Blunt', character: 'Katherine Oppenheimer', profilePath: null },
      { id: 9, name: 'Matt Damon', character: 'Leslie Groves', profilePath: null },
    ],
  },
  {
    id: 4,
    type: 'movie',
    title: 'The Kerala Story',
    year: 2023,
    rating: 7.1,
    voteCount: 85000,
    runtime: 138,
    overview: 'The story of 32,000 women from Kerala who allegedly disappeared and were converted before being recruited by the ISIS terrorist organization.',
    posterPath: 'https://image.tmdb.org/t/p/w500/pmmM2MDgYW5l9L1c0E3BKVdWoYK.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/wjOHjkp9ATIANGfX9HzCfsSPJFR.jpg',
    genres: ['drama', 'thriller'],
    language: 'hindi',
    providers: ['sonyliv', 'zee5'],
    isFree: false,
    director: 'Sudipto Sen',
    isBollywood: true,
    isTrending: true,
    aiInsight: 'A gripping, controversial narrative based on real events. Visceral storytelling that will provoke strong emotions and discussions.',
  },
  {
    id: 5,
    type: 'movie',
    title: 'Parasite',
    year: 2019,
    rating: 8.5,
    voteCount: 870000,
    runtime: 132,
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    tagline: 'Act like you own the place.',
    posterPath: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    genres: ['thriller', 'drama', 'comedy'],
    language: 'korean',
    providers: ['prime-video', 'mx-player'],
    isFree: true,
    director: 'Bong Joon Ho',
    trailerKey: '5xH0HfJHsaY',
    aiInsight: 'The rare film that works on every level — comedy, horror, social satire, thriller — all at once. A masterpiece you\'ll want to rewatch immediately.',
    isTopRated: true,
    isAIPick: true,
    isHidden: true,
    cast: [
      { id: 10, name: 'Song Kang-ho', character: 'Kim Ki-taek', profilePath: null },
      { id: 11, name: 'Lee Sun-kyun', character: 'Park Dong-ik', profilePath: null },
    ],
  },
  {
    id: 6,
    type: 'movie',
    title: '12th Fail',
    year: 2023,
    rating: 9.0,
    voteCount: 195000,
    runtime: 147,
    overview: 'A story about a UP lad from a humble family, who despite failing his 12th grade exam, chooses to pursue his dream of becoming an IPS officer.',
    tagline: 'Based on true events.',
    posterPath: 'https://image.tmdb.org/t/p/w500/5BWbxOZLEBbgAFDGCPl5Dk6R9c5.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/zxQhv3kNOfGBd9LzxnTMcv1o5u2.jpg',
    genres: ['drama', 'biography'],
    language: 'hindi',
    providers: ['jiohotstar'],
    isFree: false,
    director: 'Vidhu Vinod Chopra',
    isTopRated: true,
    isBollywood: true,
    isAIPick: true,
    aiInsight: 'One of the most emotionally powerful Hindi films in years. Raw, authentic, and deeply inspiring. You will feel the weight of every struggle.',
  },
  {
    id: 7,
    type: 'movie',
    title: 'Barbie',
    year: 2023,
    rating: 6.9,
    voteCount: 530000,
    runtime: 114,
    overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. When they get a chance to go to the real world, Barbie sets out on a journey of self-discovery.',
    tagline: 'She\'s everything. He\'s just Ken.',
    posterPath: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/nHf61UzkfFno5X1ofIjWpbVj2bA.jpg',
    genres: ['comedy', 'fantasy'],
    language: 'english',
    providers: ['prime-video', 'zee5'],
    isFree: false,
    director: 'Greta Gerwig',
    isTrending: true,
    isHollywood: true,
    aiInsight: 'Far smarter than the marketing suggested. A sharp, funny, genuinely moving film about identity and expectation. Ken is also a revelation.',
  },
  {
    id: 8,
    type: 'movie',
    title: 'Animal',
    year: 2023,
    rating: 7.0,
    voteCount: 155000,
    runtime: 201,
    overview: 'The bond between a father and his son grows intense as the son becomes possessively overprotective of his father to the extent of becoming violent and ruthless.',
    posterPath: 'https://image.tmdb.org/t/p/w500/oaGvjB0DvdhXhOAuQPTGkaryp8H.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/599GSfKaOeYOxNXlRBFPDRBifXJ.jpg',
    genres: ['action', 'drama', 'thriller'],
    language: 'hindi',
    providers: ['netflix'],
    isFree: false,
    director: 'Sandeep Reddy Vanga',
    isTrending: true,
    isBollywood: true,
    aiInsight: 'Polarizing by design. An operatic, maximalist take on toxic masculinity that demands you engage with its excesses on its own terms.',
  },
  {
    id: 9,
    type: 'movie',
    title: 'Past Lives',
    year: 2023,
    rating: 7.9,
    voteCount: 210000,
    runtime: 106,
    overview: 'Nora and Hae Sung, two deeply connected childhood friends, are separated when Nora\'s family emigrates from South Korea. They lose touch for 20 years until they are reunited in New York for one week.',
    tagline: 'Some things can\'t be undone.',
    posterPath: 'https://image.tmdb.org/t/p/w500/k3waqVXSnäher.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/aE8PcRhAkKKxQAZFJ4dpMEMEPNO.jpg',
    genres: ['romance', 'drama'],
    language: 'korean',
    providers: ['prime-video', 'apple-tv'],
    isFree: false,
    director: 'Celine Song',
    isTopRated: true,
    isAIPick: true,
    isHidden: true,
    aiInsight: 'Devastatingly quiet and precise. The kind of film that reframes how you think about all the paths not taken in your own life.',
  },
  {
    id: 10,
    type: 'movie',
    title: 'Maharaja',
    year: 2024,
    rating: 8.4,
    voteCount: 95000,
    runtime: 155,
    overview: 'A barber named Maharaja seeks justice for the brutal attack on his daughter, but the truth he uncovers is far more dangerous than expected.',
    posterPath: 'https://image.tmdb.org/t/p/w500/hqkCVJmOBvQUKwxM4YVZ4HqIgAm.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/cxRRB7aeCOF7DBDMrCJbHAoJLKz.jpg',
    genres: ['action', 'thriller', 'crime'],
    language: 'tamil',
    providers: ['netflix'],
    isFree: false,
    director: 'Nithilan Swaminathan',
    isTrending: true,
    isBollywood: true,
    isTopRated: true,
    aiInsight: 'Vijay Sethupathi at his absolute best. A tightly constructed revenge thriller where every narrative choice lands perfectly.',
  },
  {
    id: 11,
    type: 'movie',
    title: 'Poor Things',
    year: 2023,
    rating: 8.0,
    voteCount: 310000,
    runtime: 141,
    overview: 'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
    tagline: 'An adventure in self-discovery.',
    posterPath: 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXIRmGOTMGNpkzQ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
    genres: ['comedy', 'drama', 'fantasy', 'romance'],
    language: 'english',
    providers: ['jiohotstar'],
    isFree: false,
    director: 'Yorgos Lanthimos',
    isHollywood: true,
    isTopRated: true,
    isAIPick: true,
    isHidden: true,
    aiInsight: 'A fever dream of a film. Visually unlike anything else made in years. Emma Stone\'s performance is a career-best — raw, funny, and deeply human.',
  },
  {
    id: 12,
    type: 'tv',
    title: 'The Bear',
    year: 2022,
    rating: 8.7,
    voteCount: 245000,
    runtime: 30,
    overview: 'A young chef from the fine dining world returns to Chicago to run his family\'s sandwich shop.',
    posterPath: 'https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/aUPbHiLS6WyONsoFEBBUmoOR4sS.jpg',
    genres: ['drama', 'comedy'],
    language: 'english',
    providers: ['jiohotstar'],
    isFree: false,
    director: 'Christopher Storer',
    isTopRated: true,
    isHollywood: true,
    isAIPick: true,
    isTrending: true,
    aiInsight: 'The most stressful 30 minutes of television ever made — in the best possible way. Season 2, episode 7 is a masterclass in editing.',
  },
  {
    id: 13,
    type: 'tv',
    title: 'Mirzapur',
    year: 2018,
    rating: 8.4,
    voteCount: 175000,
    runtime: 52,
    overview: 'A ruthless crime saga following the rise and fall of gangsters in the heartlands of Uttar Pradesh.',
    posterPath: 'https://image.tmdb.org/t/p/w500/nWNcRTFdSHFm41yMoH8P9bHUfz7.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/c06iFGIjWA6TJyvPGcCRnYO5MCMY.jpg',
    genres: ['crime', 'thriller', 'drama'],
    language: 'hindi',
    providers: ['prime-video'],
    isFree: false,
    director: 'Gurmmeet Singh',
    isTrending: true,
    isBollywood: true,
    aiInsight: 'The definitive Hindi crime saga. Visceral, brutal, and impossibly bingeable. Munna Bhaiya is one of Indian TV\'s all-time characters.',
  },
  {
    id: 14,
    type: 'tv',
    title: 'Shogun',
    year: 2024,
    rating: 8.9,
    voteCount: 185000,
    runtime: 60,
    overview: 'Set in feudal Japan, an English navigator finds himself embroiled in a violent struggle for power that will determine the future of Japan.',
    posterPath: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSrHFuOoTXyNMGOm.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/bnzAKoXV7YAjVMBMFVjMD4lNOHs.jpg',
    genres: ['drama', 'action', 'mystery'],
    language: 'english',
    providers: ['jiohotstar'],
    isFree: false,
    director: 'Rachel Kondo',
    isTopRated: true,
    isTrending: true,
    isHollywood: true,
    isAIPick: true,
    aiInsight: 'Possibly the best limited series of the decade. Every episode feels like a feature film. The performances are extraordinary.',
  },
  {
    id: 15,
    type: 'movie',
    title: 'Kantara',
    year: 2022,
    rating: 8.3,
    voteCount: 145000,
    runtime: 150,
    overview: 'A rebellious man clashes with his tribe\'s powerful traditional guardians as ancestral forces awaken in the forests of coastal Karnataka.',
    tagline: 'Where land is God.',
    posterPath: 'https://image.tmdb.org/t/p/w500/wEKKTQWi2S3eFvQI0dRnrpIXX2P.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/gMJngTNfaqCSCqGD4y8lVMZXyfE.jpg',
    genres: ['action', 'drama', 'mystery'],
    language: 'hindi',
    providers: ['netflix', 'prime-video'],
    isFree: false,
    director: 'Rishab Shetty',
    isTopRated: true,
    isBollywood: true,
    isTrending: true,
    aiInsight: 'A primal, mythological experience like nothing else in Indian cinema. The final 20 minutes are electrifying.',
  },
  {
    id: 16,
    type: 'movie',
    title: 'Killers of the Flower Moon',
    year: 2023,
    rating: 7.6,
    voteCount: 285000,
    runtime: 206,
    overview: 'Members of the Osage Nation are murdered under mysterious circumstances in the 1920s, sparking a major FBI investigation.',
    posterPath: 'https://image.tmdb.org/t/p/w500/dB6jeFtEBvCcYhPf19JUgLnzMJQ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/1X7vow16X7CnCoexXh4H4F2yDJv.jpg',
    genres: ['crime', 'drama', 'biography'],
    language: 'english',
    providers: ['apple-tv'],
    isFree: false,
    director: 'Martin Scorsese',
    isHollywood: true,
    isTopRated: true,
    aiInsight: 'Scorsese\'s most morally complex film since The Departed. DiCaprio has never been better at being worse.',
  },
  {
    id: 17,
    type: 'movie',
    title: 'Stree 2',
    year: 2024,
    rating: 7.8,
    voteCount: 120000,
    runtime: 135,
    overview: 'The horror-comedy sequel returns to Chanderi, where a new supernatural threat emerges as the town continues to deal with the mysterious Stree.',
    posterPath: 'https://image.tmdb.org/t/p/w500/placeholder-stree2.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/placeholder-stree2-backdrop.jpg',
    genres: ['comedy', 'horror'],
    language: 'hindi',
    providers: ['prime-video'],
    isFree: false,
    director: 'Amar Kaushik',
    isBollywood: true,
    isTrending: true,
    aiInsight: 'Shraddha Kapoor and Rajkummar Rao deliver gold again. The perfect blend of horror and comedy that the franchise is known for.',
  },
  {
    id: 18,
    type: 'movie',
    title: 'All Quiet on the Western Front',
    year: 2022,
    rating: 7.8,
    voteCount: 310000,
    runtime: 148,
    overview: 'A young German soldier\'s harrowing experiences and disillusionment during World War I.',
    posterPath: 'https://image.tmdb.org/t/p/w500/hgGmADsFMzZlzUfewJuPANHDRWY.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/ByDWFoFaGlN72WchSXlT0QVAhsL.jpg',
    genres: ['drama', 'action'],
    language: 'english',
    providers: ['netflix'],
    isFree: false,
    director: 'Edward Berger',
    isTopRated: true,
    isHollywood: true,
    isHidden: true,
    aiInsight: 'Brutal, necessary cinema. The anti-war film of a generation. The last 30 minutes are almost unbearable to watch — in the best way.',
  },
  {
    id: 19,
    type: 'movie',
    title: 'Gulabo Sitabo',
    year: 2020,
    rating: 6.5,
    voteCount: 42000,
    runtime: 131,
    overview: 'A quirky landlord and his wily tenant scheme against each other until a bureaucrat and archaeologist come along and outfox them both.',
    posterPath: 'https://image.tmdb.org/t/p/w500/4uMRzfCbNOEYJxgmPOJK0GJSVSJ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/a0PcJZfEHXjSMiSv6GAvbGKEWJQ.jpg',
    genres: ['comedy', 'drama'],
    language: 'hindi',
    providers: ['prime-video'],
    isFree: false,
    director: 'Shoojit Sircar',
    isBollywood: true,
    isHidden: true,
    aiInsight: 'A small, quirky delight. Amitabh Bachchan is unrecognizable and magnificent. Perfect for a lazy afternoon when you want something different.',
  },
  {
    id: 20,
    type: 'movie',
    title: 'Everything Everywhere All at Once',
    year: 2022,
    rating: 7.8,
    voteCount: 580000,
    runtime: 139,
    overview: 'An aging Chinese immigrant is swept up in an insane adventure where she alone can save existence by exploring other universes connecting with the lives she could have led.',
    tagline: 'The universe is so much bigger than you realize.',
    posterPath: 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/feSiISwgEpVzR1v3zv2n2NSa3AC.jpg',
    genres: ['sci-fi', 'comedy', 'action', 'drama'],
    language: 'english',
    providers: ['prime-video', 'mx-player'],
    isFree: true,
    director: 'Daniel Kwan & Daniel Scheinert',
    isTopRated: true,
    isHollywood: true,
    isAIPick: true,
    isHidden: true,
    aiInsight: 'The most creative film of the decade. Part chaotic action movie, part meditation on regret and love. It should not work but it absolutely does.',
  },
  {
    id: 21,
    type: 'tv',
    title: 'Panchayat',
    year: 2020,
    rating: 9.0,
    voteCount: 98000,
    runtime: 35,
    overview: 'A city-educated man is posted as a Panchayat secretary in a remote village in Uttar Pradesh. He now must adapt to his new surroundings.',
    posterPath: 'https://image.tmdb.org/t/p/w500/placeholder-panchayat.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/placeholder-panchayat-backdrop.jpg',
    genres: ['comedy', 'drama'],
    language: 'hindi',
    providers: ['prime-video'],
    isFree: false,
    director: 'Deepak Kumar Mishra',
    isBollywood: true,
    isTopRated: true,
    isAIPick: true,
    aiInsight: 'The most charming, warmhearted Hindi series ever made. Slow-burn excellence that sneaks up on you and then makes you cry unexpectedly.',
  },
  {
    id: 22,
    type: 'movie',
    title: 'Mission: Impossible — Dead Reckoning',
    year: 2023,
    rating: 7.7,
    voteCount: 275000,
    runtime: 163,
    overview: 'Ethan Hunt and his IMF team must track down a terrifying new weapon before it falls into the wrong hands.',
    posterPath: 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/1hJJoONEFSPqfLvbwkETVDJO1lR.jpg',
    genres: ['action', 'thriller'],
    language: 'english',
    providers: ['prime-video', 'sonyliv'],
    isFree: false,
    director: 'Christopher McQuarrie',
    isHollywood: true,
    isTrending: true,
    aiInsight: 'Tom Cruise doing things no 60-year-old should be doing. Pure action cinema at its most committed and spectacular.',
  },
  {
    id: 23,
    type: 'movie',
    title: 'Taare Zameen Par',
    year: 2007,
    rating: 8.4,
    voteCount: 215000,
    runtime: 162,
    overview: 'An eight year old boy is thought to be a lazy troublemaker, until the new art teacher has the patience and compassion to discover the true cause of his struggles.',
    posterPath: 'https://image.tmdb.org/t/p/w500/yd7QVJX0PPKU1JJFZ1OKPzFLGMH.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/vb3jXhkPnilV7tXZq1hMPeJfYt0.jpg',
    genres: ['drama'],
    language: 'hindi',
    providers: ['prime-video', 'mx-player'],
    isFree: true,
    director: 'Aamir Khan',
    isBollywood: true,
    isTopRated: true,
    isHidden: true,
    aiInsight: 'One of Hindi cinema\'s most emotionally complete films. A tearjerker that earns every tear through genuine character work.',
  },
  {
    id: 24,
    type: 'movie',
    title: 'The Whale',
    year: 2022,
    rating: 7.7,
    voteCount: 188000,
    runtime: 117,
    overview: 'A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter.',
    posterPath: 'https://image.tmdb.org/t/p/w500/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/eERnKHCaNgZLFovfedVuPJGKHMB.jpg',
    genres: ['drama'],
    language: 'english',
    providers: ['prime-video'],
    isFree: false,
    director: 'Darren Aronofsky',
    isHollywood: true,
    isHidden: true,
    aiInsight: 'Brendan Fraser\'s extraordinary, devastating comeback. Intimate chamber drama that will wreck you emotionally.',
  },
  {
    id: 25,
    type: 'tv',
    title: 'Scam 1992',
    year: 2020,
    rating: 9.3,
    voteCount: 155000,
    runtime: 55,
    overview: 'The story of stockbroker Harshad Mehta, who took the Indian stock market to giddy heights and then its tumultuous fall.',
    posterPath: 'https://image.tmdb.org/t/p/w500/placeholder-scam.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/original/placeholder-scam-backdrop.jpg',
    genres: ['crime', 'biography', 'drama'],
    language: 'hindi',
    providers: ['sonyliv'],
    isFree: false,
    director: 'Hansal Mehta',
    isBollywood: true,
    isTopRated: true,
    isAIPick: true,
    aiInsight: 'The definitive Indian biographical drama. Pratik Gandhi is mesmerizing as Harshad Mehta — a performance for the ages. SonyLIV\'s crown jewel.',
  },
];

// ===========================
// Curated Lists
// ===========================
export const getTrendingMovies = () => MOVIES.filter(m => m.isTrending).slice(0, 10);
export const getTopRatedMovies = () => MOVIES.filter(m => m.isTopRated).slice(0, 10);
export const getFreeMovies = () => MOVIES.filter(m => m.isFree).slice(0, 10);
export const getAIPicks = () => MOVIES.filter(m => m.isAIPick).slice(0, 8);
export const getBollywoodMovies = () => MOVIES.filter(m => m.isBollywood).slice(0, 10);
export const getHollywoodMovies = () => MOVIES.filter(m => m.isHollywood).slice(0, 10);
export const getHiddenGems = () => MOVIES.filter(m => m.isHidden).slice(0, 8);
export const getMovieById = (id: number) => MOVIES.find(m => m.id === id);

export const getMoodBasedRecommendation = (_moods: string[], genres: string[]): Movie => {
  const filtered = MOVIES.filter(m => {
    const genreMatch = genres.length === 0 || m.genres.some(g => genres.includes(g));
    return genreMatch;
  });
  if (filtered.length === 0) return MOVIES[Math.floor(Math.random() * MOVIES.length)];
  return filtered[Math.floor(Math.random() * filtered.length)];
};

// ===========================
// Actors
// ===========================
export const ACTORS: Actor[] = [
  { id: 1, name: 'Timothée Chalamet', profilePath: null, knownFor: ['Dune', 'Call Me By Your Name', 'Little Women'] },
  { id: 2, name: 'Zendaya', profilePath: null, knownFor: ['Dune', 'Euphoria', 'Spider-Man'] },
  { id: 3, name: 'Vijay Sethupathi', profilePath: null, knownFor: ['Maharaja', '96', 'Master'] },
  { id: 4, name: 'Alia Bhatt', profilePath: null, knownFor: ['RRR', 'Gangubai Kathiawadi', 'Raazi'] },
  { id: 5, name: 'Cillian Murphy', profilePath: null, knownFor: ['Oppenheimer', 'Peaky Blinders', 'Batman Begins'] },
];

// ===========================
// AI Explanation Templates
// ===========================
export const generateAIExplanation = (movie: Movie, moods: string[]): string => {
  if (movie.aiInsight) return movie.aiInsight;
  return `Based on your ${moods.join(' and ')} mood, ${movie.title} delivers exactly what you're looking for — a ${movie.genres.slice(0, 2).join(' and ')} experience that will keep you engaged for its entire ${movie.runtime}-minute runtime.`;
};
